name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SECRET: ${{ secrets.SECRET }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run cargo check
        run: cargo check --all-targets
